"""
Associative Memory (Memory Stream)
===================================
The "brain" of an agent — stores everything that ever happened.

Think of it as a diary with three sections:
- Events:  things the agent saw happen ("Isabella is cooking breakfast")
- Thoughts: insights generated by reflecting ("I should try new recipes")
- Chats:   conversations between agents ("Isabella and Maria discussed the party")

Each entry is a "ConceptNode" — a structured memory with:
- SPO triple: (Subject, Predicate, Object) — e.g., ("Isabella", "is", "cooking")
- Description: human-readable text
- Embedding: a vector of numbers representing the meaning (for similarity search)
- Poignancy: importance score 1-10 (assigned by the LLM)
- Keywords: for fast lookup by topic

Retrieval: when an agent needs to remember something, we search by:
1. Recency — newer memories score higher (exponential decay: 0.99^age)
2. Relevance — cosine similarity between the query and memory embeddings
3. Importance — higher poignancy = more likely to be retrieved
"""
import datetime
import json
import os


class ConceptNode:
    """
    A single memory entry. Each node stores one thing that happened,
    one thought, or one conversation.

    Fields explained:
    - node_id: unique identifier (e.g., "node_1", "node_2")
    - node_count: global counter across all node types
    - type_count: counter within this type (e.g., 3rd event)
    - type: "event", "thought", or "chat"
    - depth: how "deep" this insight is (0=perceived, 1=first reflection, 2=reflection on reflection, ...)
    - created: when this memory was formed
    - expiration: when this memory should be forgotten (thoughts expire in 30 days)
    - last_accessed: updated each time this memory is retrieved (for recency calculation)
    - subject/predicate/object: the SPO triple (structured representation)
    - description: human-readable text
    - embedding_key: the text used to generate the embedding vector
    - poignancy: importance score 1-10 (higher = more important)
    - keywords: set of words for fast keyword-based lookup
    - filling: list of node_ids that support this insight (evidence chain)
    """
    def __init__(self, node_id, node_count, type_count, node_type, depth,
                 created, expiration, s, p, o,
                 description, embedding_key, poignancy, keywords, filling):
        self.node_id = node_id
        self.node_count = node_count
        self.type_count = type_count
        self.type = node_type
        self.depth = depth
        self.created = created
        self.expiration = expiration
        self.last_accessed = self.created  # newly created = just accessed
        self.subject = s
        self.predicate = p
        self.object = o
        self.description = description
        self.embedding_key = embedding_key
        self.poignancy = poignancy
        self.keywords = keywords
        self.filling = filling

    def spo_summary(self):
        """Return the (subject, predicate, object) tuple for deduplication."""
        return (self.subject, self.predicate, self.object)


class AssociativeMemory:
    """
    The full memory system. Contains three sequences (lists) of memories:
    - seq_event:  things that happened (perceived actions)
    - seq_thought: reflections and insights (generated by the agent itself)
    - seq_chat:   conversations between agents

    Also maintains keyword indexes for fast lookup:
    - kw_to_event:  keyword → list of event nodes
    - kw_to_thought: keyword → list of thought nodes
    - kw_to_chat:   keyword → list of chat nodes

    And keyword strength counters (how many times a keyword appeared):
    - kw_strength_event: keyword → count
    - kw_strength_thought: keyword → count
    """
    def __init__(self):
        self.id_to_node = {}       # node_id → ConceptNode (master lookup)
        self.seq_event = []        # chronological list of events (newest first)
        self.seq_thought = []      # chronological list of thoughts (newest first)
        self.seq_chat = []         # chronological list of chats (newest first)
        self.kw_to_event = {}      # keyword → [event nodes]
        """
        kw_to_event example:
        {
        "kitchen": [
            {
            "node_id": "node_412",
            "node_count": 412,
            "type_count": 184,
            "node_type": "observation",
            "depth": 0,
            "created": 1716625800,
            "expiration": null,
            "s": "stove",
            "p": "is",
            "o": "burning",
            "description": "The kitchen stove is turned on and a pot of water is boiling.",
            "embedding_key": [0.0123, -0.0456, 0.789, 0.123],
            "poignancy": 6,
            "keywords": ["stove", "kitchen", "water"],
            "filling": null
            },
            {
            "node_id": "node_390",
            "node_count": 390,
            "type_count": 170,
            "node_type": "observation",
            "depth": 0,
            "created": 1716624900,
            "expiration": null,
            "s": "coffee_maker",
            "p": "is",
            "o": "brewing",
            "description": "The coffee maker is brewing a fresh pot of coffee.",
            "embedding_key": [0.0912, 0.0234, -0.112, 0.543],
            "poignancy": 2,
            "keywords": ["coffee", "kitchen"],
            "filling": null
            }
        ],
        "stove": [
            {
            "node_id": "node_412",
            "node_count": 412,
            "type_count": 184,
            "node_type": "observation",
            "depth": 0,
            "created": 1716625800,
            "expiration": null,
            "s": "stove",
            "p": "is",
            "o": "burning",
            "description": "The kitchen stove is turned on and a pot of water is boiling.",
            "embedding_key": [0.0123, -0.0456, 0.789, 0.123],
            "poignancy": 6,
            "keywords": ["stove", "kitchen", "water"],
            "filling": null
            }
        ]
        }
        """
        self.kw_to_thought = {}    # keyword → [thought nodes]
        self.kw_to_chat = {}       # keyword → [chat nodes]
        self.kw_strength_event = {}   # keyword → how many times it appeared in events
        self.kw_strength_thought = {} # keyword → how many times it appeared in thoughts
        self.embeddings = {}       # text → embedding vector (cached)

    def add_event(self, created, expiration, s, p, o,
                  description, keywords, poignancy, embedding_key, embedding, filling):
        """
        Add a new event to memory.

        An event is something the agent PERCEIVED — another agent's action,
        something happening in the world, etc.

        Args:
            created: datetime when this happened
            expiration: when to forget (None = never)
            s, p, o: subject, predicate, object (e.g., "Isabella", "is", "cooking")
            description: human-readable text
            keywords: set of words for indexing (e.g., {"isabella", "cooking", "kitchen"})
            poignancy: importance 1-10
            embedding_key: text used to generate the embedding
            embedding: the vector (list of floats) for similarity search
            filling: evidence nodes (usually empty for events)

        Returns:
            The created ConceptNode
        """
        # Generate unique IDs
        node_count = len(self.id_to_node) + 1
        type_count = len(self.seq_event) + 1
        node_type = "event"
        node_id = f"node_{node_count}"
        depth = 0  # Events are depth 0 (directly perceived)

        # Create the node
        node = ConceptNode(node_id, node_count, type_count, node_type, depth,
                           created, expiration, s, p, o,
                           description, embedding_key, poignancy, keywords, filling)

        # Insert at front of event list (newest first)
        self.seq_event.insert(0, node)

        # Index by keywords for fast lookup
        for kw in keywords:
            kw_lower = kw.lower()
            if kw_lower in self.kw_to_event:
                # insert(0, node) is used to insert the node at the beginning of the list
                self.kw_to_event[kw_lower].insert(0, node)
            else:
                self.kw_to_event[kw_lower] = [node]

        # Register in master lookup
        self.id_to_node[node_id] = node

        # Track keyword strength (how often each keyword appears)
        # Skip "idle" actions — they're not interesting
        if f"{p} {o}" != "is idle":
            for kw in keywords:
                kw_lower = kw.lower()
                # get() is used to get the value of the key, if the key is not found, it will return 0
                self.kw_strength_event[kw_lower] = self.kw_strength_event.get(kw_lower, 0) + 1 

        # Cache the embedding vector
        self.embeddings[embedding_key] = embedding
        return node

    def add_thought(self, created, expiration, s, p, o,
                    description, keywords, poignancy, embedding_key, embedding, filling):
        """
        Add a new THOUGHT to memory.

        Thoughts are INSIGHTS generated by the agent during reflection.
        Example: "I noticed I keep cooking alone, maybe I should invite Maria."

        Key difference from events:
        - Depth starts at 1 (not 0) — it's one level removed from direct perception
        - Has "filling" — evidence nodes that support this insight
        - Depth increases if evidence is itself a thought (reflection on reflection)
        """
        node_count = len(self.id_to_node) + 1
        type_count = len(self.seq_thought) + 1
        node_type = "thought"
        node_id = f"node_{node_count}"

        # Thoughts start at depth 1. If the evidence includes deeper thoughts,
        # this thought's depth = 1 + max(evidence depths)
        depth = 1
        try:
            if filling:
                depth += max([self.id_to_node[i].depth for i in filling])
        except:
            pass  # If a filling node doesn't exist, keep depth at 1

        node = ConceptNode(node_id, node_count, type_count, node_type, depth,
                           created, expiration, s, p, o,
                           description, embedding_key, poignancy, keywords, filling)

        self.seq_thought.insert(0, node)
        for kw in keywords:
            kw_lower = kw.lower()
            if kw_lower in self.kw_to_thought:
                self.kw_to_thought[kw_lower].insert(0, node)
            else:
                self.kw_to_thought[kw_lower] = [node]
        self.id_to_node[node_id] = node

        if f"{p} {o}" != "is idle":
            for kw in keywords:
                kw_lower = kw.lower()
                self.kw_strength_thought[kw_lower] = self.kw_strength_thought.get(kw_lower, 0) + 1

        self.embeddings[embedding_key] = embedding
        return node

    def add_chat(self, created, expiration, s, p, o,
                 description, keywords, poignancy, embedding_key, embedding, filling):
        """
        Add a new CHAT to memory.

        Chats are conversations between two agents.
        Example: "Isabella talked to Maria about the party."

        Stored separately from events so we can look up conversation history.
        """
        node_count = len(self.id_to_node) + 1
        type_count = len(self.seq_chat) + 1
        node_type = "chat"
        node_id = f"node_{node_count}"
        depth = 0  # Chats are directly perceived (depth 0)

        node = ConceptNode(node_id, node_count, type_count, node_type, depth,
                           created, expiration, s, p, o,
                           description, embedding_key, poignancy, keywords, filling)

        self.seq_chat.insert(0, node)
        for kw in keywords:
            kw_lower = kw.lower()
            if kw_lower in self.kw_to_chat:
                self.kw_to_chat[kw_lower].insert(0, node)
            else:
                self.kw_to_chat[kw_lower] = [node]
        self.id_to_node[node_id] = node
        self.embeddings[embedding_key] = embedding
        return node

    def retrieve_relevant_events(self, s_content, p_content, o_content):
        """
        Find events matching the given subject, predicate, or object.

        Example: retrieve_relevant_events("Isabella", "is", "cooking")
        → returns all events where "isabella", "is", or "cooking" appear as keywords.

        Uses keyword index for fast lookup (O(1) per keyword).
        Returns a set (no duplicates).
        """
        contents = [s_content, p_content, o_content]
        ret = []
        for i in contents:
            if i and i.lower() in self.kw_to_event:
                ret += self.kw_to_event[i.lower()]
        return set(ret)

    def retrieve_relevant_thoughts(self, s_content, p_content, o_content):
        """Same as retrieve_relevant_events but searches thoughts."""
        contents = [s_content, p_content, o_content]
        ret = []
        for i in contents:
            if i and i.lower() in self.kw_to_thought:
                ret += self.kw_to_thought[i.lower()]
        return set(ret)

    def get_embedding(self, text):
        """
        Look up the cached embedding vector for a given text.
        Returns None if the text hasn't been embedded yet.
        """
        return self.embeddings.get(text, None)

    def get_summarized_latest_events(self, retention):
        """
        Return SPO tuples of the N most recent events.

        Used for deduplication: before adding a new event, check if the
        same (subject, predicate, object) was already perceived recently.

        Args:
            retention: how many recent events to check (e.g., 5)
        """
        ret_set = set()
        for e_node in self.seq_event[:retention]:
            ret_set.add(e_node.spo_summary())
        return ret_set

    def get_last_chat(self, target_persona_name):
        """
        Find the most recent chat with a specific person.

        Example: get_last_chat("Maria") → the latest chat node where Maria was involved.
        Returns None if no chat with that person exists.
        """
        if target_persona_name.lower() in self.kw_to_chat:
            return self.kw_to_chat[target_persona_name.lower()][0]
        return None

    def save(self, out_dir):
        """
        Save all memory data to disk (3 files):
        - nodes.json: all ConceptNodes with their metadata
        - embeddings.json: cached embedding vectors
        - kw_strength.json: keyword frequency counters
        """
        os.makedirs(out_dir, exist_ok=True)

        # Serialize nodes (iterate backwards to match original order)
        r = {}
        for count in range(len(self.id_to_node), 0, -1):
            node_id = f"node_{count}"
            node = self.id_to_node[node_id]
            r[node_id] = {
                "node_count": node.node_count,
                "type_count": node.type_count,
                "type": node.type,
                "depth": node.depth,
                "created": node.created.strftime('%Y-%m-%d %H:%M:%S'),
                "expiration": node.expiration.strftime('%Y-%m-%d %H:%M:%S') if node.expiration else None,
                "subject": node.subject,
                "predicate": node.predicate,
                "object": node.object,
                "description": node.description,
                "embedding_key": node.embedding_key,
                "poignancy": node.poignancy,
                "keywords": list(node.keywords),
                "filling": node.filling,
            }
        with open(os.path.join(out_dir, "nodes.json"), "w") as f:
            json.dump(r, f, indent=2)
        with open(os.path.join(out_dir, "embeddings.json"), "w") as f:
            json.dump(self.embeddings, f)
        with open(os.path.join(out_dir, "kw_strength.json"), "w") as f:
            json.dump({"kw_strength_event": self.kw_strength_event,
                       "kw_strength_thought": self.kw_strength_thought}, f)
