"""
Chat Module — Generate Conversations Between Agents
====================================================
When two agents are at the same location and both are free,
they can start a conversation. The LLM generates what each
agent says based on their personality and relationship.

Two conversation types:
- small_talk: 1-5 rounds, casual greeting or quick exchange
- deep_talk: 6-20 rounds, meaningful conversation

Each round = one message from each agent.
One round = 2 minutes of game time.

Connection to the paper:
    Section 4.5 — "Agents engage in conversations with each other.
    The dialogue is generated by the LLM based on the agents'
    personalities and their relationship."
"""
import datetime
from agent.prompts import get_prompts


def generate_round(persona, other_persona, llm_client):
    """
    Generate one round of conversation between two agents.

    Each agent generates one message. The conversation is stored
    in both agents' chat_history.

    Args:
        persona: the agent generating the message
        other_persona: the other agent in the conversation
        llm_client: API client for text generation

    Returns:
        dict with {"from": name, "msg": message}
    """
    prompts = get_prompts()

    # Format chat history so far
    history_text = _format_history(persona.scratch.chat_history)

    # Build the prompt
    prompt = prompts.CHAT_PROMPT.format(
        identity=persona.scratch.get_str_iss(),
        my_action=persona.scratch.act_description or "doing something",
        other_name=other_persona.name,
        other_action=other_persona.scratch.act_description or "doing something",
        chat_type=persona.scratch.chat_type or "small_talk",
        current_round=persona.scratch.chat_total_rounds - persona.scratch.chat_rounds_left + 1,
        total_rounds=persona.scratch.chat_total_rounds,
        chat_history=history_text if history_text else "(start of conversation)"
    )

    response = llm_client.generate(prompt, system_prompt=prompts.SYSTEM_PROMPT)
    if not response:
        return None

    # Parse the message
    message = _parse_message(response)

    # Store in chat history
    entry = {"from": persona.name, "msg": message}
    persona.scratch.chat_history.append(entry)

    return entry


def generate_reply(persona, other_persona, llm_client):
    """
    Generate a reply from the other agent in the conversation.

    Args:
        persona: the agent who just spoke
        other_persona: the agent generating the reply
        llm_client: API client for text generation

    Returns:
        dict with {"from": name, "msg": message}
    """
    prompts = get_prompts()

    # Format chat history so far
    history_text = _format_history(other_persona.scratch.chat_history)

    # Build the prompt
    prompt = prompts.CHAT_PROMPT.format(
        identity=other_persona.scratch.get_str_iss(),
        my_action=other_persona.scratch.act_description or "doing something",
        other_name=persona.name,
        other_action=persona.scratch.act_description or "doing something",
        chat_type=other_persona.scratch.chat_type or "small_talk",
        current_round=other_persona.scratch.chat_total_rounds - other_persona.scratch.chat_rounds_left + 1,
        total_rounds=other_persona.scratch.chat_total_rounds,
        chat_history=history_text if history_text else "(start of conversation)"
    )

    response = llm_client.generate(prompt, system_prompt=prompts.SYSTEM_PROMPT)
    if not response:
        return None

    # Parse the message
    message = _parse_message(response)

    # Store in chat history
    entry = {"from": other_persona.name, "msg": message}
    other_persona.scratch.chat_history.append(entry)

    return entry


def generate_summary(persona, other_persona, llm_client):
    """
    Generate a summary of the conversation after it ends.

    The summary is stored in both agents' associative memory.

    Args:
        persona: one agent in the conversation
        other_persona: the other agent
        llm_client: API client for text generation

    Returns:
        summary text string
    """
    prompts = get_prompts()

    # Format the full conversation
    history_text = _format_history(persona.scratch.chat_history)
    if not history_text:
        return None

    # Generate summary
    prompt = prompts.SUMMARY_PROMPT.format(
        name=persona.name,
        other_name=other_persona.name,
        chat_history=history_text
    )

    summary = llm_client.generate(prompt, system_prompt=prompts.SYSTEM_PROMPT)
    if not summary:
        return None

    return summary.strip()


def store_chat_memory(persona, other_name, summary, llm_client):
    """
    Store conversation summary in agent's associative memory.

    Stores as both a chat node and an event node.

    Args:
        persona: the agent storing the memory
        other_name: name of the other agent
        summary: conversation summary text
        llm_client: API client for embeddings
    """
    created = persona.scratch.curr_time
    expiration = created + datetime.timedelta(days=30)
    keywords = set(summary.lower().split()[:5])
    embedding = llm_client.get_embedding(summary)

    # Store as chat node (uses full add_chat signature)
    persona.a_mem.add_chat(
        created, expiration,
        persona.name, "chatted_with", other_name,
        summary, keywords, 6,
        summary, embedding, []
    )


def clear_chat_state(persona):
    """
    Clear conversation state after it ends.

    Sets cooldown so the agent doesn't start a new conversation immediately.
    """
    other_name = persona.scratch.chatting_with

    # Set cooldown: can't chat with same agent for 1 hour
    if other_name and persona.scratch.curr_time:
        persona.scratch.last_chat_with[other_name] = persona.scratch.curr_time

    # Set general cooldown: can't chat at all for 30 minutes
    if persona.scratch.curr_time:
        persona.scratch.chat_cooldown_until = persona.scratch.curr_time + datetime.timedelta(minutes=30)

    # Clear chat state
    persona.scratch.chatting_with = None
    persona.scratch.chat_type = None
    persona.scratch.chat_rounds_left = 0
    persona.scratch.chat_total_rounds = 0
    persona.scratch.chat_history = []
    persona.scratch.chat = None


def can_chat(persona, other_name):
    """
    Check if the agent can start a new conversation.

    Checks both per-pair cooldown (1 hour) and general cooldown (30 min).

    Args:
        persona: the agent wanting to chat
        other_name: name of the potential conversation partner

    Returns:
        True if the agent can chat, False otherwise
    """
    now = persona.scratch.curr_time
    if not now:
        return False

    # Check general cooldown
    if persona.scratch.chat_cooldown_until and now < persona.scratch.chat_cooldown_until:
        return False

    # Check per-pair cooldown (1 hour)
    last_chat = persona.scratch.last_chat_with.get(other_name)
    if last_chat:
        elapsed = (now - last_chat).total_seconds() / 60  # minutes
        if elapsed < 60:
            return False

    return True


def _format_history(history):
    """Format chat history as readable text."""
    if not history:
        return ""
    lines = []
    for entry in history:
        lines.append(f"{entry['from']}: {entry['msg']}")
    return "\n".join(lines)


def _parse_message(response):
    """Parse LLM response to extract the message."""
    # Try to find "message: " prefix
    for line in response.strip().split("\n"):
        line = line.strip()
        if line.lower().startswith("message:"):
            return line[len("message:"):].strip()
    # Fallback: use the whole response
    return response.strip()
